[package]
name = "rust-kernal"
version = "0.1.0"
authors = ["aloggia <aloggia22@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"